baseURL = "https://www.nams.site/"
languageCode = "zh-cn"
title = "Nam's"
theme = "hugo-cactus-theme"
googleAnalytics = "UA-176417735-1"
disqusShortname = "nams-2"

[params]
	name = "Nam"
	description = "Nam's blog"
	bio = ""
	# 创建robots.txt，建议设置为true
	enableRobotsTXT = true
	# Enter optionally your twitter account
	# twitter = "Your Twitter account"
	enableRSS = true

	# Integrate Javascript files or stylesheets by adding the url to the external assets or by
	# linking local files with their path relative to the static folder, e.g. "css/styles.css"
	customCSS = []
	customJS  = []

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	subscribe = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "写最简单的代码，做最单纯的人"
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "mono-social"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    # twitter  = "https://www.twitter.com/"
    # facebook = "https://www.facebook.com/"
    github   = "https://Lennam.github.com/"
    # dribble  = "https://www.dribbble.com/"
